import uuid
import subprocess
import tempfile
import os
from typing import Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.db.session import get_projects

router = APIRouter()


class GenerateRequest(BaseModel):
    title: str
    prompt: str
    meta: Optional[dict] = None


@router.post("/{project_id}/generate")
async def generate_project(project_id: uuid.UUID, request: GenerateRequest):
    projects = get_projects()
    pid = str(project_id)
    projects[pid] = {
        "id": pid,
        "title": request.title,
        "prompt": request.prompt,
        "meta": request.meta,
        "status": "queued",
    }
    return {"message": "Generation pipeline dispatched", "project_id": pid}


@router.get("/{project_id}/download")
async def download_project(project_id: uuid.UUID):
    """
    Generate and return a placeholder MP4 for the project using FFmpeg.
    The video shows the project title as animated text on a gradient background.
    """
    projects = get_projects()
    pid = str(project_id)
    project = projects.get(pid)

    title = project["title"] if project else "AnimateAI Project"
    # Sanitize title for FFmpeg drawtext (escape special chars)
    safe_title = title.replace("'", "\\'").replace(":", "\\:").replace("\\", "\\\\")[:40]

    # Create a temp file for the output video
    tmp = tempfile.NamedTemporaryFile(suffix=".mp4", delete=False)
    tmp.close()
    out_path = tmp.name

    try:
        # FFmpeg: 8-second cinematic placeholder video
        # - Dark gradient background
        # - AnimateAI branding text
        # - Project title overlay
        # - Fade in/out
        cmd = [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", (
                "color=c=0x0f172a:size=1920x1080:rate=30,"
                "format=yuv420p"
            ),
            "-vf", (
                f"drawtext=text='AnimateAI':fontsize=48:fontcolor=0x6366f1:"
                f"x=(w-text_w)/2:y=(h/2)-80:alpha='if(lt(t,1),t,if(lt(t,7),1,8-t))',"
                f"drawtext=text='{safe_title}':fontsize=72:fontcolor=white:"
                f"x=(w-text_w)/2:y=(h/2):alpha='if(lt(t,1.5),0,if(lt(t,2.5),t-1.5,if(lt(t,7),1,8-t)))',"
                f"drawtext=text='Generated by AI Pipeline':fontsize=32:fontcolor=0x94a3b8:"
                f"x=(w-text_w)/2:y=(h/2)+90:alpha='if(lt(t,2),0,if(lt(t,3),t-2,if(lt(t,7),1,8-t)))'"
            ),
            "-t", "8",
            "-c:v", "libx264",
            "-preset", "ultrafast",
            "-crf", "28",
            out_path
        ]

        result = subprocess.run(cmd, capture_output=True, timeout=60)
        if result.returncode != 0:
            raise HTTPException(
                status_code=500,
                detail=f"FFmpeg error: {result.stderr.decode()[:500]}"
            )

        filename = f"{title[:30].replace(' ', '_')}_AnimateAI.mp4"
        return FileResponse(
            path=out_path,
            media_type="video/mp4",
            filename=filename,
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=504, detail="Video generation timed out")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/{project_id}/scenes/{scene_id}/regenerate-assets")
async def regenerate_scene_assets(project_id: uuid.UUID, scene_id: uuid.UUID):
    return {"message": f"Dispatched asset regeneration for scene {scene_id}"}


@router.post("/{project_id}/scenes/{scene_id}/regenerate-voice")
async def regenerate_scene_voice(project_id: uuid.UUID, scene_id: uuid.UUID):
    return {"message": f"Dispatched voice regeneration for scene {scene_id}"}


class TimelineUpdate(BaseModel):
    ordered_scene_ids: list[str]


@router.put("/{project_id}/timeline")
async def update_timeline(project_id: uuid.UUID, update: TimelineUpdate):
    return {"message": "Timeline updated successfully", "new_order": update.ordered_scene_ids}


@router.delete("/{project_id}/scenes/{scene_id}")
async def delete_scene(project_id: uuid.UUID, scene_id: uuid.UUID):
    return {"message": f"Scene {scene_id} deleted"}
