import uuid
import subprocess
import tempfile
import os
from typing import Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.db.session import get_projects

router = APIRouter()


class GenerateRequest(BaseModel):
    title: str
    prompt: str
    meta: Optional[dict] = None


@router.post("/{project_id}/generate")
async def generate_project(project_id: uuid.UUID, request: GenerateRequest):
    projects = get_projects()
    pid = str(project_id)
    projects[pid] = {
        "id": pid,
        "title": request.title,
        "prompt": request.prompt,
        "meta": request.meta,
        "status": "queued",
    }
    return {"message": "Generation pipeline dispatched", "project_id": pid}


@router.get("/{project_id}/download")
async def download_project(project_id: uuid.UUID):
    """
    Generate and return a placeholder MP4 using FFmpeg.
    """
    projects = get_projects()
    pid = str(project_id)
    project = projects.get(pid)
    title = project["title"] if project else "AnimateAI Project"

    # Sanitize: remove characters that break FFmpeg drawtext
    safe_title = ""
    for ch in title[:35]:
        if ch.isalnum() or ch in " .,!?-_":
            safe_title += ch
        else:
            safe_title += " "
    safe_title = safe_title.strip() or "AnimateAI Project"

    tmp = tempfile.NamedTemporaryFile(suffix=".mp4", delete=False)
    tmp.close()
    out_path = tmp.name

    try:
        # Simple, reliable FFmpeg command — no complex filters
        cmd = [
            "ffmpeg", "-y",
            "-f", "lavfi",
            # Dark navy background
            "-i", "color=c=0x0f172a:size=1920x1080:rate=24",
            "-vf", (
                # AnimateAI label top
                "drawtext=text='AnimateAI':"
                "fontsize=52:fontcolor=0x6366f1:"
                "x=(w-text_w)/2:y=(h/2)-100,"
                # Project title center
                f"drawtext=text='{safe_title}':"
                "fontsize=80:fontcolor=white:"
                "x=(w-text_w)/2:y=(h/2),"
                # Subtitle bottom
                "drawtext=text='Generated by AI Pipeline':"
                "fontsize=34:fontcolor=0x94a3b8:"
                "x=(w-text_w)/2:y=(h/2)+110"
            ),
            "-t", "8",
            "-pix_fmt", "yuv420p",
            "-c:v", "libx264",
            "-preset", "ultrafast",
            "-crf", "30",
            out_path,
        ]

        result = subprocess.run(cmd, capture_output=True, timeout=60)

        if result.returncode != 0 or not os.path.exists(out_path) or os.path.getsize(out_path) == 0:
            # Fallback: plain black video with no text (guaranteed to work)
            fallback_cmd = [
                "ffmpeg", "-y",
                "-f", "lavfi", "-i", "color=c=black:size=1280x720:rate=24",
                "-t", "5", "-pix_fmt", "yuv420p",
                "-c:v", "libx264", "-preset", "ultrafast",
                out_path,
            ]
            subprocess.run(fallback_cmd, capture_output=True, timeout=30)

        safe_filename = safe_title.replace(" ", "_") + "_AnimateAI.mp4"
        return FileResponse(
            path=out_path,
            media_type="video/mp4",
            filename=safe_filename,
        )

    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=504, detail="Video generation timed out")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/{project_id}/scenes/{scene_id}/regenerate-assets")
async def regenerate_scene_assets(project_id: uuid.UUID, scene_id: uuid.UUID):
    return {"message": f"Dispatched asset regeneration for scene {scene_id}"}


@router.post("/{project_id}/scenes/{scene_id}/regenerate-voice")
async def regenerate_scene_voice(project_id: uuid.UUID, scene_id: uuid.UUID):
    return {"message": f"Dispatched voice regeneration for scene {scene_id}"}


class TimelineUpdate(BaseModel):
    ordered_scene_ids: list[str]


@router.put("/{project_id}/timeline")
async def update_timeline(project_id: uuid.UUID, update: TimelineUpdate):
    return {"message": "Timeline updated successfully", "new_order": update.ordered_scene_ids}


@router.delete("/{project_id}/scenes/{scene_id}")
async def delete_scene(project_id: uuid.UUID, scene_id: uuid.UUID):
    return {"message": f"Scene {scene_id} deleted"}
